name: Test crw-build token for authenticated connection to RHEC

on: 
  pull_request:
jobs:
  build:
    name: Build stuff
    runs-on: ubuntu-latest
    env:
      CRW_BUILD_USER: ${{ secrets.CRW_BUILD_USER }}
      CRW_BUILD_TOKEN: ${{ secrets.CRW_BUILD_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to RHEC
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CRW_BUILD_USER }}
          password: ${{ secrets.CRW_BUILD_TOKEN }}
          registry: registry.redhat.io
      - name: Test authenticated connection
        shell: bash
        run: |
          set -x
          set +e
          echo "[INFO]: Log into registry.redhat.io as ${{ CRW_BUILD_USER }} ..."
          echo "${{ CRW_BUILD_TOKEN }}" | docker login -u="${{ CRW_BUILD_USER }}" --password-stdin registry.redhat.io
          docker pull registry.redhat.io/codeready-workspaces/imagepuller-rhel8:2.5
